ecommerce/ecom/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.remove_cart,name='remove_cart'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecommerce/ecom/ecom/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                            document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                            document_root=settings.MEDIA_ROOT)   

ecommerce/ecom/searchapp/urls.py
from django.urls import path
from . import views
app_name = 'searchapp'

urlpatterns = [
    path('',views.SearchResult,name="SearchResult"),
]

ecommerce/ecom/shop/urls.py
from django.urls import path
from . import views
app_name = 'shop'

urlpatterns = [
    path('',views.ProdCat,name="ProdCat"),
    path('<slug:c_slug>/',views.ProdCat,name="products_by_category"),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProDetail,name="ProdCatDetail"),
]

ecommerce/ecom/cart/models.py
from django.db import models
import cart
from shop.models import Product

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=200,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return  self.product.price * self.quantity          

    def __str__(self):
        return '{}'.format(self.product)    

ecommerce/ecom/searchapp/models.py
from django.db import models

# Create your models here.

ecommerce/ecom/shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250,unique=True)
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])
        

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)       
    slug = models.SlugField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='product',blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:ProdCatDetail',args=[self.category.slug,self.slug])    

    def __str__(self):
        return '{}'.format(self.name)

ecommerce/ecom/cart/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
    except  Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=cart_id(request))
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity +=1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')

def cart_detail(request,counter=0,total=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)   
            counter += cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict( cart_items=cart_items,total=total,counter=counter))                             


def remove_cart(request,product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')   

def full_remove(request,product_id): 
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product,id=product_id)
    cart_item = CartItem.objects.get(product=product,cart=cart)
    cart_item.delete() 
    return redirect('cart:cart_detail')       

ecommerce/ecom/searchapp/views.py
from django.shortcuts import render
from shop.models import Product
# Create your views here.


def SearchResult(request):
    query = None
    products = None
    if request.method == 'POST':
        query = request.POST['searched']
        products = Product.objects.all().filter(name__contains=query)
    # if 'q' in request.GET:
    #     query = request.GET('searched')
    #     products = Product.objects.filter(Q(name__contains=query))
    return render(request,"search.html",{'query1':query,'products':products})    

ecommerce/ecom/shop/views.py
from django.shortcuts import get_object_or_404, render
from .models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.

def ProdCat(request,c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category,slug=c_slug)    
        products_list = Product.objects.all().filter(category=c_page,available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list,8)
    try:
        page = int(request.GET.get('page','1'))   
    except:
        page=1
    try:
        products = paginator.page(page)
    except(EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)             
    return render(request,"category.html",{'category':c_page,'products':products})        

def ProDetail(request,c_slug,product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise e    
    return render(request,"product.html",{'product':product})    

ecommerce/ecom/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="desc" content="{% block metadesc %}{% endblock %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    
    <div class="container-fluid">
        <!-- {% include 'header.html' %} -->
        {% include 'navbar.html' %}
        {% block content%}
        {% endblock %}
    </div>
    <hr>
        
{% include 'footer.html' %}

        <script src="{% static 'js/popper.min.js' %}"></script>    
        <script src="{% static 'js/bootstrap.min.js' %}"></script>    
</body>
</html>

ecommerce/ecom/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadesc %}
   Cart Shortlist      
{% endblock %}
{% block title %}
Cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center" style="height: 400px;">
        <h3>Your cart is empty</h3>
        <p>Click here-->
            <a href="{% url 'shop:ProdCat' %}" class="btn btn-warning">Continue shopping</a>
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <h1>Your Cart</h1>
    </div>
</div>
    <div class="row">
        <div class="col-12 col-lg-6 col-md-12 text-center">
            <table class="table table-bordered bg-light">
                <thead>
                    <th colspan="5">Your items</th>
                </thead>
                <tbody>
                    {% for cart_item in cart_items %}
                    <tr>
                        <td>
                            <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" class="float-left rounded" alt="Product img" width="200px" height="200px"></a>
                        </td>
                        <td>
                            {{cart_item.product.name}}
                            <br>
                         SKU :{{cart_item.product.id}}
                            <br>
                        Price:{{cart_item.product.price}}
                            <br>
                        Qty  :<b>({{cart_item.quantity}})</b> x {{cart_item}}        
                        </td>
                        <td>
                            ${{cart_item.sub_total}}
                        </td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                        <td>
                            <a href="{% url 'cart:add_cart' cart_item.product.id %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
                            &nbsp;<a href="{% url 'cart:remove_cart' cart_item.product.id %}"><i class="fa fa-minus" aria-hidden="true"></i></a>
                            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                        {% else %}
                        <td>
                            &nbsp;<a href="{% url 'cart:remove_cart' cart_item.product.id %}"><i class="fa fa-minus" aria-hidden="true"></i></a>
                            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a>
                        </td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-12 col-lg-6 col-md-12 text-center">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            Checkout
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            Please check your cart before the payment. 
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Total amount is :<strong>{{total}}</strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div>
                <a href="{% url 'shop:ProdCat' %}" class="btn btn-warning">Continue Shopping</a>
            </div>

        </div>
    </div>
</div>
{% endif %}

{% endblock %}

ecommerce/ecom/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadesc %}
    {% if category %}
        {{ category.desc|truncatewords:155 }}
    {% else %}
        Welcome to ECOM Store,the garden of EVERYTHING...
    {% endif %}        
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} - ECOM Store
    {% else %}
        Our collections- ECOM Store
    {% endif %}        
{% endblock %}
{% block content %}
    {% if category %}
        <div>
            <div>
                <p><a href="{% url 'shop:ProdCat' %}" style="text-decoration: none;" class="text-dark">All Products</a></p>
            </div>
        </div>
    {% endif %}
        <div>   
        {% if category %}
        <img src="{{category.img.url}}" alt="{{category.name}}" width="100px" height="100px">
        </div> 
        <div>
            <h3>{{category.name}}</h3>
            <p>{{category.desc}}</p>
        </div>
    {% else %} 
        <div class="my_banner">
            <img src="{% static 'ecom_banner.png' %}" alt="our products" width="100%" height="600px">
        </div>
        <hr>
        <div class="p-5">
            <h3 class="text-center"><strong>Our Collections</strong></h3>
            <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </div>
    {% endif %} 
        <div class="row p-5 mb-3">
            {% for product in products.object_list %}
            <div class="col-xl-3 col-12 col-md-4 mb-3">               
                <div class="card text-center shadow" style="width: 20rem;">
                    <a href="{{product.get_url}}"><img src="{{product.img.url}}" alt="{{product.name}}" width="250px" height="250px"></a>
                    <div class="card-body justify-content-center">                        
                        <div>
                            <h5><b>{{product.name}}</b></h5>
                            <p>$ {{product.price}}</p>
                        </div>
                    </div>
                </div>               
            </div>
            {% endfor %}
        </div>
        <div class="mx-auto">
            {% if products.paginator.num_pages > 1 %}

            <hr>
            <div class="text-center">
                {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active{% endif %}">{{pg}}</a>
                {% endfor %}
            </div>
            {% endif %}
        </div>
{% endblock %}

ecommerce/ecom/templates/footer.html
<footer>
    <div class="footer text-bottom foot">
        <p>&copy; Ecom Pvt Ltd.All rights reserved</p>
    </div>
</footer>

ecommerce/ecom/templates/header.html
{% load static %}
<header>
    <div>
        <a href="{% url 'shop:ProdCat' %}"><img src="{% static 'logo.png' %}" alt="logo" width="150px" height="150px"></a>
    </div>
</header>

ecommerce/ecom/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light p-4">
    <div class="container-fluid">
      <div class="col-xl-6 col-md-6 col-6">
        <a href="{% url 'shop:ProdCat' %}"><img src="{% static 'logo2.png' %}" alt="logo" width="100px" height="60px"></a>
      </div>
      <div class="col-xl-6 col-md-6 col-6">
      <button class="navbar-toggler mx-auto"  type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 pl-5">
          <li class="nav-item">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Shop
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'shop:ProdCat' %}">All Products</a></li>
              {% for cat in links %}
              <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% if item_count > 0 %}
          <li class="nav-item">
            <a href="{% url 'cart:cart_detail' %}" class="nav-link"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Cart ({{item_count}})</a>
          </li>
          {% endif %}
        </ul>
        <form class="d-flex" action="{% url 'searchapp:SearchResult' %}" method="POST">
            {% csrf_token %}
          <input class="form-control me-2" type="search" placeholder="Search" name="searched" aria-label="Search">
          <button class="btn btn-outline-dark" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
        </form>
      </div>
    </div>
    </div>
  </nav>

ecommerce/ecom/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadesc %}

        {{ product.desc|truncatewords:155 }}

{% endblock %}
{% block title %}
    {% if category %}
        {{ product.name }} - ECOM Store
    {% endif %}        
{% endblock %}
{% block content %}
<div>
    <div>
        <p><a class="my_link" style="text-decoration: none; " href="{% url 'shop:ProdCat' %}">Home</a> | <a style="text-decoration: none;" href="product.category.get_url">{{product.category}}</a> | {{product.name}}</p>
    </div>
</div>
<div class="row">
    <div class="col-xl-5">
        <div>
            <img src="{{product.img.url}}" alt="{{product.name}}" width="500px" height="500px">
        </div>
    </div>
    <div class="col-xl-7 mt-5">
        <div>
            <h3>{{product.name}}</h3>
            <h5>${{product.price}}</h5>
            <p><b><u>Specifications</u></b></p>
            <p>{{product.desc}}</p>
            {% if product.stock <= 0 %}
            <p class="text-danger"><b>Out Of Stock</b></p>
            {% else %}
            <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-primary"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Add To Cart</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/ecom/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadesc %}
   We have plenty of products...      
{% endblock %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center">You have searched for :<b>"{{query1}}"</b></p>
</div>
<div class="row p-5 mb-3">
    {% for product in products %}
    <div class="col-xl-3 col-12 col-md-4 mb-3">               
        <div class="card text-center shadow" style="width: 20rem;">
            <a href="{{product.get_url}}"><img src="{{product.img.url}}" alt="{{product.name}}" width="250px" height="250px"></a>
            <div class="card-body justify-content-center">                        
                <div>
                    <h5><b>{{product.name}}</b></h5>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>               
    </div>
    {% empty %}
    <div class="mx-auto">
        <p class="text-center">0 results found</p>
    </div>
    {% endfor %}
</div>
{% endblock %}